apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-hola
  namespace: micro
spec:
  selector:
    matchLabels:
      app: micro-hola
  replicas: 1
  template:
    metadata:
      labels:
        app: micro-hola
    spec:
      containers:
        - name: loopback-kubernetes
          image: ramisistemas/mavenjenkins:3.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-hola
  namespace: micro
spec:
  ports:
    - protocol: "TCP"
      port: 3000        # The port inside the cluster
      targetPort: 3000  # The port exposed by the service
  type: NodePort        # Type of service
  selector:
    app: micro-hola
