apiVersion: v1
kind: Namespace
metadata:
  name: micro
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-hola-deployment
  namespace: micro
spec:
  selector:
    matchLabels:
      app: micro-hola
  replicas: 1
  template:
    metadata:
      labels:
        app: micro-hola
    spec:
      containers:
        - name: micro-hola
          image: ramisistemas/mavenjenkins:3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: micro-svc
  namespace: micro
  labels:
    app: micro-hola
spec:
  ports:
  - port: 80
    name: micro-hola
  type: NodePort
  selector:
    app: micro-hola   
